<?php
$tickets = $this->getTicket();
$statusModel = Mage::getModel('ticket/status');
$userModel = Mage::getModel('admin/user');
// var_dump($statusModel->load($tickets->getStatusId()));die;
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ticket Details</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            font-size: 18px;
            text-align: left;
        }

        th,
        td {
            padding: 12px;
            border: 1px solid #ddd;
        }

        th {
            background-color: #f4f4f4;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
    </style>
</head>

<body>
    <h1>Ticket Details</h1>
    <table>
        <thead>
            <tr>
                <th>Ticket Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Priority</th>
                <th>Assigned By</th>
                <th>Assigned To</th>
                <th>Status</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($tickets as $ticket): ?>
                <tr style="background-color:<?php echo $statusModel->load($ticket->getStatusId())->getColourCode()?>;">
                    <td><?php echo htmlspecialchars($ticket->getId()); ?></td>
                    <td><?php echo htmlspecialchars($ticket->getTitle()); ?></td>
                    <td><?php echo nl2br(htmlspecialchars($ticket->getDescription())); ?></td>
                    <td><?php echo htmlspecialchars($ticket->getPriority()); ?></td>
                    <td><?php echo ucfirst(htmlspecialchars($userModel->load($ticket->getAssignedBY())->getUsername())) ?></td>
                    <td><?php echo ucfirst(htmlspecialchars($userModel->load($ticket->getAssignedTo())->getUsername())) ?></td>
                    <td><?php echo htmlspecialchars($statusModel->load($ticket->getStatus())->getLabel()); ?></td>
                    <td><?php echo htmlspecialchars($ticket->getCreatedAt()); ?></td>
                    <td><?php echo htmlspecialchars($ticket->getUpdatedAt()); ?></td>
                    <td><a href="<?php echo $this->getUrl('*/*/view') ?>"><button>View</button></a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>

</html>