<?php
$sellers = $this->getSeller();
?>
<div id="report-container">
    <select name="seller" id="seller">
        <option value="">Select Seller</option>
        <?php foreach ($sellers as $id => $name): ?>
            <option value="<?php echo $id; ?>"><?php echo $this->escapeHtml($name); ?></option>
        <?php endforeach; ?>
    </select>
    <button id="load-report" type="button">Load Report</button>
    <div id="products-grid" style="border: 1px;"></div>
</div>


<script type="text/javascript">
    document.observe('dom:loaded', function () {

        $('load-report').observe('click', function () {
            var sellerId = $F('seller');
            new Ajax.Request('<?php echo Mage::getUrl('*/*/loadProducts'); ?>', {
                parameters: { seller_id: sellerId },
                post: 'POST',
                onSuccess: function (response) {
                    // console.log(JSON.parse(response.responseText));
                    $('products-grid').innerHTML = "";
                    var data = JSON.parse(response.responseText);
                    var table = new Element('table');
                    table.border="1";
                    var thead = new Element('thead');
                    var headerRow = new Element('tr');
                    ['Id','Name', 'Sku'].forEach(function (header) {
                        headerRow.insert(new Element('th').update(header));
                    });
                    thead.insert(headerRow);
                    table.insert(thead);

                    var tbody = new Element('tbody');
                    data.forEach(function (item) {
                        var row = new Element('tr');
                        var reportType = (item.report_type == 1) ? 'Product' : 'Customer';
                        // row.insert(new Element('td').input(checkbox));
                        row.insert(new Element('td').update(item.entity_id));
                        row.insert(new Element('td').update(item.name));
                        row.insert(new Element('td').update(item.sku));
                        tbody.insert(row);
                    });
                    table.insert(tbody);
                    $('products-grid').insert(table);

                }
            })
        })
    });
</script>